---

antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Module 1"
    - name: module-02
      label: "Module 2"
    - name: module-03
      label: "Module 3"

tabs:
  - name: terminal
    port: 443
    path: /wetty
